# Generated by Django 4.2 on 2023-06-29 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='products',
        ),
        migrations.AddField(
            model_name='cart',
            name='complete',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
